language: node_js
node_js:
- lts/*
services:
- docker

script:
- npm install
- npm run docker:build:toolchain
- npm run docker:build:games
- npm run build
- npm run docker:build:server
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD && docker push fredrikaleksander/browser-arcade:latest