language: node_js
node_js:
- lts/*
services:
- docker

before_install:
- docker pull fredrikaleksander/browser-arcade-toolchain:latest

script:
- npm install
- npm run docker:build:full
- npm run build